function(lazperf_add_library _target)
    message(STATUS "Adding lazperf library: ${_target} ${BUILD_SHARED_LIBS}")
    if (${BUILD_SHARED_LIBS})
      add_library(${_target} SHARED ${ARGN})
    else()
      add_library(${_target} STATIC ${ARGN})
    endif()
    lazperf_library_compile_settings(${_target} )
    lazperf_install_library(${_target})
endfunction()
